{
    "name": "HomeAssistant",
    "version": "0.0.6",
    "icon": "fad fa-house",
    "category": "household",
    "author": "Lazza",
    "maintainers": [],
    "desc": "Connect alice to your home assistant",
    "aliceMinVersion": "1.0.0-b2",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        ""
    ],
    "conditions": {
        "lang": [
            "en"
        ],
        "asrArbitraryCapture": true
    }
}
